/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Benjami' at '27.1.2017 16:43' with Gradle 3.0
 *
 * @author Benjami, @date 27.1.2017 16:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
